[ENH] Added nightly docker build to synced workflows
neurobagel/workflows pull request #108
Opened 2024-09-26 16:05 UTC by rmanaem

- Closes #92

## Checklist
_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [x] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

2024-09-27 13:29 UTC, surchs requested changes
hey @rmanaem, thanks a lot for taking this on!

I have a minor suggestions about the sync thing and one bigger one about the workflow template. Take a look and see if we can make the workflow simpler / more like the regular build one

2024-09-27 13:29 UTC, surchs commented on .github/sync.yml
> +  # Workflow for releasing docker nightly
```suggestion
  # Workflow for building docker nightly
```

2024-09-27 13:29 UTC, surchs commented on .github/sync.yml
> +      neurobagel/federation-api
Let's copy the nightly docker build workflow next to the release docker build workflow here in the file. That'll make it easier to grasp the difference

2024-09-27 13:29 UTC, surchs commented on .github/sync.yml
> +      neurobagel/federation-api
In fact, wouldn't it be possible to just add the nightly-build-docker workflow to the list of files we're already pushing to repos with the release-build-docker thing?

2024-09-27 13:29 UTC, surchs commented on template_workflows/build_docker_nightly.yaml
> +            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name == 'query-tool' ? 'query_tool' : (github.event.repository.name == 'federation-api' ? 'federation_api' : github.event.rep
Why do you have to do this by hand? The regular release build workflow uses `steps.meta.outputs.tags`. I am not familiar with the workflow, I believe you and @alyssadai created it. But I would expect that you can just use a similar logic to automate the image name here and change the version tag to `nightly`

2024-09-27 15:35 UTC, rmanaem commented on template_workflows/build_docker_nightly.yaml
> +            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name == 'query-tool' ? 'query_tool' : (github.event.repository.name == 'federation-api' ? 'federation_api' : github.event.rep
Oh yea the docker metadata action, I forgot about that.

2024-09-27 15:36 UTC, rmanaem commented on .github/sync.yml
> +      neurobagel/federation-api
Yea just gotta delete the docker build workflow from UI and tools repos too

2024-09-27 15:38 UTC, alyssadai commented on template_workflows/build_docker_nightly.yaml
> +            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name == 'query-tool' ? 'query_tool' : (github.event.repository.name == 'federation-api' ? 'federation_api' : github.event.rep
Actually, I don't think you even need to use that. The key thing you need is the Docker repo name, which is already a GH actions variable in every repo, because the `build_docker_on_release.yml` wf also relies on it:

https://github.com/neurobagel/workflows/blob/a6c24bb2bd902ea0985e0d638240a1a7d1a39a07/template_workflows/auto_release/build_docker_on_release.yml#L30

so you can just refer to the variable directly

2024-09-27 15:43 UTC, alyssadai reviewed
Hey @rmanaem, sorry for the duplicate review (I assigned myself but forgot to submit) - see my comment on using the repo-level `DOCKERHUB_REPO` variable to fetch the Docker repo name!

Also, 🍒: for consistency with other wfs in this repo, can we use .yml instead of .yaml for this file?

2024-09-27 22:11 UTC, surchs approved these changes
Very nice! :tada: 

:cook:

2024-09-28 02:47 UTC, alyssadai approved these changes
Looks good! Just one fix below to the file name in sync.yml, otherwise 🧑‍🍳

2024-09-28 02:47 UTC, alyssadai commented on .github/sync.yml
> +        dest: .github/workflows/build_docker_nightly.yaml
```suggestion
      - source: template_workflows/build_docker_nightly.yml
        dest: .github/workflows/build_docker_nightly.yml
```

2024-09-30 15:55 UTC, merged